# -*- coding: utf-8 -*-
"""Rnn-Sentiment-Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rYdmOfNa0ZFD9jpFr5t-weVmbUHYCews
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("suchintikasarkar/sentiment-analysis-for-mental-health")

print("Path to dataset files:", path)

import pandas as pd
import os
import glob # Import glob for searching files

# The original line caused a FileNotFoundError.
# We will now dynamically find the correct CSV file.
# csv_file_path = os.path.join(path, 'mental_health.csv')

print(f"Searching for CSV files in: {path}")
# List all CSV files in the directory and its subdirectories
csv_files = glob.glob(os.path.join(path, '**', '*.csv'), recursive=True)

if not csv_files:
    print("Error: No CSV files found in the dataset directory.")
    print(f"Contents of {path}: {os.listdir(path)}")
    raise FileNotFoundError(f"No CSV files found in {path}. Please check the dataset structure.")
elif len(csv_files) == 1:
    csv_file_path = csv_files[0]
    print(f"Found one CSV file: {csv_file_path}")
else:
    print(f"Multiple CSV files found: {csv_files}")
    print("Attempting to select a primary CSV file. If this is not correct, please update `csv_file_path` manually.")
    # Try to find a file with 'mental_health' in its name, otherwise pick the first.
    potential_main_csv = next((f for f in csv_files if 'mental_health' in os.path.basename(f).lower()), csv_files[0])
    csv_file_path = potential_main_csv
    print(f"Selected CSV file: {csv_file_path}")

# Read the CSV file into a pandas DataFrame using the discovered path
df = pd.read_csv(csv_file_path)

# Display the first 5 rows of the DataFrame
display(df.head())

df['status'].unique()

df['status'].value_counts()

df.isna().sum()

df['status']

"""### Text Distribution: Sentence Length"""

df['statement_length'] = df['statement'].astype(str).apply(len)

print("Descriptive statistics for statement length:")
display(df['statement_length'].describe())

avg_sentence_length = df['statement_length'].mean()
print(f"\nAverage sentence length: {avg_sentence_length:.2f} characters")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.histplot(df['statement_length'], bins=50, kde=True)
plt.title('Distribution of Statement Lengths')
plt.xlabel('Statement Length (characters)')
plt.ylabel('Frequency')
plt.show()

import re
import nltk
from nltk.corpus import stopwords
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = ' '.join([word for word in text.split() if word not in stop_words])
    return text

df_cleaned = df.dropna(subset=['statement']).copy()
df_cleaned['cleaned_statement'] = df_cleaned['statement'].apply(clean_text)

max_words = 10000
max_len = 100

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(df_cleaned['cleaned_statement'])
sequences = tokenizer.texts_to_sequences(df_cleaned['cleaned_statement'])

word_index = tokenizer.word_index
print(f'Found {len(word_index)} unique tokens.')

X = pad_sequences(sequences, maxlen=max_len)
display(X.shape)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_words = 10000
max_len = 100

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(df_cleaned['cleaned_statement'])

sequences = tokenizer.texts_to_sequences(df_cleaned['cleaned_statement'])
word_index = tokenizer.word_index
X = pad_sequences(sequences, maxlen=max_len)

print(f'Unique tokens: {len(word_index)}')
print(f'Shape of data tensor: {X.shape}')

from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense

le = LabelEncoder()
df_cleaned['label'] = le.fit_transform(df_cleaned['status'])
num_classes = df_cleaned['label'].nunique()

model = Sequential([
    Embedding(input_dim=max_words, output_dim=64, input_length=max_len),
    SimpleRNN(64),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

from sklearn.model_selection import train_test_split
from tensorflow.keras.optimizers import Adam

X_train, X_test, y_train, y_test = train_test_split(X, df_cleaned['label'].values, test_size=0.2, random_state=42)

optimizer = Adam(learning_rate=0.001)
model.compile(optimizer=optimizer, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

history = model.fit(
    X_train,
    y_train,
    epochs=5,
    batch_size=64,
    validation_data=(X_test, y_test)
)

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

y_pred_probs = model.predict(X_test)
y_pred = np.argmax(y_pred_probs, axis=1)
print(f"Accuracy_score", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred, target_names=le.classes_))

cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', xticklabels=le.classes_, yticklabels=le.classes_, cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

"""### Task 8 — Real-Time Prediction
Testing the trained Simple RNN model with custom, unseen sentences to evaluate its real-world monitoring capability.
"""

def predict_real_time(text):
    cleaned_text = clean_text(text)
    sequence = tokenizer.texts_to_sequences([cleaned_text])
    padded_sequence = pad_sequences(sequence, maxlen=max_len)

    prediction = model.predict(padded_sequence, verbose=0)
    class_index = np.argmax(prediction)
    confidence = np.max(prediction)

    sentiment = le.inverse_transform([class_index])[0]
    return sentiment, confidence

test_sentences = [
    "I had a great day today and I feel very productive.",
    "I am so worried about the future, my heart keeps racing.",
    "Everything feels hopeless and I can't find a reason to get out of bed.",
    "Sometimes I feel like I have too much energy and I can't stop talking.",
    "The pressure at work is becoming unbearable and I'm constantly exhausted."
]

for sentence in test_sentences:
    sentiment, confidence = predict_real_time(sentence)
    print(f"Text: {sentence}")
    print(f"Predicted Status: {sentiment} ({confidence*100:.2f}% confidence)")
    print("-" * 30)

user_input = input("Enter a text message to analyze: ")
if user_input:
    sentiment, confidence = predict_real_time(user_input)
    print(f"\nInput: {user_input}")
    print(f"Predicted Status: {sentiment}")
    print(f"Confidence Score: {confidence*100:.2f}%")

import pickle

model.save('mental_health_rnn_model.h5')
model.save('mental_health_rnn_model.keras')

with open('tokenizer.pkl', 'wb') as handle:
    pickle.dump(tokenizer, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('label_encoder.pkl', 'wb') as handle:
    pickle.dump(le, handle, protocol=pickle.HIGHEST_PROTOCOL)

print("Model (H5 and Keras formats), tokenizer, and label encoder saved successfully.")

